/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.skincare.view;

import java.awt.Color;

/**
 *
 * @author mhmha
 */
public class Home extends javax.swing.JFrame {

    Color paneDefault;
    Color paneClicked;
    
    public Home() {
        initComponents();
        
        paneDefault = new Color(0, 179, 60);
        paneClicked = new Color(242,242,242);
        DashboardPaneClicked.setBackground(paneClicked);
        PaymentPaneClicked.setBackground(paneDefault);
        AppointmentPaneClicked.setBackground(paneDefault);
        DoctorPaneClicked.setBackground(paneDefault);
        SchedulePaneClicked.setBackground(paneDefault);
        
        jDesktopPane1.removeAll();
        DashboardFrame m2 = new DashboardFrame();
        jDesktopPane1.add(m2).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DashboardPane = new javax.swing.JPanel();
        DashboardPaneClicked = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AppointmentPane = new javax.swing.JPanel();
        AppointmentPaneClicked = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DoctorPane = new javax.swing.JPanel();
        DoctorPaneClicked = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SchedulePane = new javax.swing.JPanel();
        SchedulePaneClicked = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPane5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PaymentPane = new javax.swing.JPanel();
        PaymentPaneClicked = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 255, 238));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(69, 84, 74));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 30, 40));

        jPanel2.setBackground(new java.awt.Color(42, 111, 65));

        DashboardPane.setBackground(new java.awt.Color(11, 142, 55));
        DashboardPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboardPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DashboardPaneClickedLayout = new javax.swing.GroupLayout(DashboardPaneClicked);
        DashboardPaneClicked.setLayout(DashboardPaneClickedLayout);
        DashboardPaneClickedLayout.setHorizontalGroup(
            DashboardPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        DashboardPaneClickedLayout.setVerticalGroup(
            DashboardPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 234));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/1.png"))); // NOI18N
        jLabel2.setText("  Dashboard");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout DashboardPaneLayout = new javax.swing.GroupLayout(DashboardPane);
        DashboardPane.setLayout(DashboardPaneLayout);
        DashboardPaneLayout.setHorizontalGroup(
            DashboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPaneLayout.createSequentialGroup()
                .addComponent(DashboardPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DashboardPaneLayout.setVerticalGroup(
            DashboardPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(DashboardPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
        );

        AppointmentPane.setBackground(new java.awt.Color(11, 142, 55));
        AppointmentPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AppointmentPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AppointmentPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout AppointmentPaneClickedLayout = new javax.swing.GroupLayout(AppointmentPaneClicked);
        AppointmentPaneClicked.setLayout(AppointmentPaneClickedLayout);
        AppointmentPaneClickedLayout.setHorizontalGroup(
            AppointmentPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        AppointmentPaneClickedLayout.setVerticalGroup(
            AppointmentPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 234));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/calendars_7602649.png"))); // NOI18N
        jLabel3.setText("  Appointment");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout AppointmentPaneLayout = new javax.swing.GroupLayout(AppointmentPane);
        AppointmentPane.setLayout(AppointmentPaneLayout);
        AppointmentPaneLayout.setHorizontalGroup(
            AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentPaneLayout.createSequentialGroup()
                .addComponent(AppointmentPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AppointmentPaneLayout.setVerticalGroup(
            AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppointmentPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(AppointmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3))
        );

        DoctorPane.setBackground(new java.awt.Color(11, 142, 55));
        DoctorPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoctorPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DoctorPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DoctorPaneClickedLayout = new javax.swing.GroupLayout(DoctorPaneClicked);
        DoctorPaneClicked.setLayout(DoctorPaneClickedLayout);
        DoctorPaneClickedLayout.setHorizontalGroup(
            DoctorPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        DoctorPaneClickedLayout.setVerticalGroup(
            DoctorPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 234, 234));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/user-md-symbol_25701.png"))); // NOI18N
        jLabel4.setText("  Doctor");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout DoctorPaneLayout = new javax.swing.GroupLayout(DoctorPane);
        DoctorPane.setLayout(DoctorPaneLayout);
        DoctorPaneLayout.setHorizontalGroup(
            DoctorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorPaneLayout.createSequentialGroup()
                .addComponent(DoctorPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DoctorPaneLayout.setVerticalGroup(
            DoctorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(DoctorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4))
        );

        SchedulePane.setBackground(new java.awt.Color(11, 142, 55));
        SchedulePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SchedulePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SchedulePaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SchedulePaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SchedulePaneClickedLayout = new javax.swing.GroupLayout(SchedulePaneClicked);
        SchedulePaneClicked.setLayout(SchedulePaneClickedLayout);
        SchedulePaneClickedLayout.setHorizontalGroup(
            SchedulePaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        SchedulePaneClickedLayout.setVerticalGroup(
            SchedulePaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(234, 234, 234));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/clock_3416094.png"))); // NOI18N
        jLabel5.setText("  Schedule");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SchedulePaneLayout = new javax.swing.GroupLayout(SchedulePane);
        SchedulePane.setLayout(SchedulePaneLayout);
        SchedulePaneLayout.setHorizontalGroup(
            SchedulePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedulePaneLayout.createSequentialGroup()
                .addComponent(SchedulePaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SchedulePaneLayout.setVerticalGroup(
            SchedulePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SchedulePaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(SchedulePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
        );

        jPane5.setBackground(new java.awt.Color(11, 142, 55));
        jPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(234, 234, 234));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/tooth.png"))); // NOI18N
        jLabel6.setText(" ToothCare");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPane5Layout = new javax.swing.GroupLayout(jPane5);
        jPane5.setLayout(jPane5Layout);
        jPane5Layout.setHorizontalGroup(
            jPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPane5Layout.setVerticalGroup(
            jPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PaymentPane.setBackground(new java.awt.Color(11, 142, 55));
        PaymentPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaymentPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaymentPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PaymentPaneClickedLayout = new javax.swing.GroupLayout(PaymentPaneClicked);
        PaymentPaneClicked.setLayout(PaymentPaneClickedLayout);
        PaymentPaneClickedLayout.setHorizontalGroup(
            PaymentPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PaymentPaneClickedLayout.setVerticalGroup(
            PaymentPaneClickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(234, 234, 234));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/credit-card_726559.png"))); // NOI18N
        jLabel7.setText("  Payment");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PaymentPaneLayout = new javax.swing.GroupLayout(PaymentPane);
        PaymentPane.setLayout(PaymentPaneLayout);
        PaymentPaneLayout.setHorizontalGroup(
            PaymentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentPaneLayout.createSequentialGroup()
                .addComponent(PaymentPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PaymentPaneLayout.setVerticalGroup(
            PaymentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaymentPaneClicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PaymentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7))
        );

        btnSave.setBackground(new java.awt.Color(27, 126, 60));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(234, 234, 234));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toothcare/image/login.png"))); // NOI18N
        btnSave.setText("LOGOUT");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AppointmentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DoctorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SchedulePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PaymentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(DashboardPane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PaymentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AppointmentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoctorPane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SchedulePane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jDesktopPane1.setBackground(new java.awt.Color(230, 255, 238));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    int x, y;
    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void DashboardPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPaneMousePressed
        DashboardPaneClicked.setBackground(paneClicked);
        PaymentPaneClicked.setBackground(paneDefault);
        AppointmentPaneClicked.setBackground(paneDefault);
        DoctorPaneClicked.setBackground(paneDefault);
        SchedulePaneClicked.setBackground(paneDefault);      
    }//GEN-LAST:event_DashboardPaneMousePressed

    private void DashboardPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPaneMouseClicked
        jDesktopPane1.removeAll();
        DashboardFrame dashboard = new DashboardFrame();
        jDesktopPane1.add(dashboard).setVisible(true);
    }//GEN-LAST:event_DashboardPaneMouseClicked

    private void AppointmentPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentPaneMouseClicked
        jDesktopPane1.removeAll();
        AppointmentFrame appointmen = new AppointmentFrame();
        jDesktopPane1.add(appointmen).setVisible(true);
    }//GEN-LAST:event_AppointmentPaneMouseClicked

    private void AppointmentPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentPaneMousePressed
        DashboardPaneClicked.setBackground(paneDefault);
        PaymentPaneClicked.setBackground(paneDefault);
        AppointmentPaneClicked.setBackground(paneClicked);
        DoctorPaneClicked.setBackground(paneDefault);
        SchedulePaneClicked.setBackground(paneDefault);   
    }//GEN-LAST:event_AppointmentPaneMousePressed

    private void DoctorPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorPaneMouseClicked
        jDesktopPane1.removeAll();
        DoctorFrame doctor = new DoctorFrame();
        jDesktopPane1.add(doctor).setVisible(true);
    }//GEN-LAST:event_DoctorPaneMouseClicked

    private void DoctorPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorPaneMousePressed
        DashboardPaneClicked.setBackground(paneDefault);
        PaymentPaneClicked.setBackground(paneDefault);
        AppointmentPaneClicked.setBackground(paneDefault);
        DoctorPaneClicked.setBackground(paneClicked);
        SchedulePaneClicked.setBackground(paneDefault);   
    }//GEN-LAST:event_DoctorPaneMousePressed

    private void SchedulePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SchedulePaneMouseClicked
        jDesktopPane1.removeAll();
        ScheduleFrame schedule = new ScheduleFrame();
        jDesktopPane1.add(schedule).setVisible(true);
    }//GEN-LAST:event_SchedulePaneMouseClicked

    private void SchedulePaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SchedulePaneMousePressed
        DashboardPaneClicked.setBackground(paneDefault);
        PaymentPaneClicked.setBackground(paneDefault);
        AppointmentPaneClicked.setBackground(paneDefault);
        DoctorPaneClicked.setBackground(paneDefault);
        SchedulePaneClicked.setBackground(paneClicked);    
    }//GEN-LAST:event_SchedulePaneMousePressed

    private void PaymentPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentPaneMouseClicked

        jDesktopPane1.removeAll();
        PaymentFrame payment = new PaymentFrame();
        jDesktopPane1.add(payment).setVisible(true);
    }//GEN-LAST:event_PaymentPaneMouseClicked

    private void PaymentPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentPaneMousePressed
        DashboardPaneClicked.setBackground(paneDefault);
        PaymentPaneClicked.setBackground(paneClicked);
        AppointmentPaneClicked.setBackground(paneDefault);
        DoctorPaneClicked.setBackground(paneDefault);
        SchedulePaneClicked.setBackground(paneDefault);   
    }//GEN-LAST:event_PaymentPaneMousePressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppointmentPane;
    private javax.swing.JPanel AppointmentPaneClicked;
    private javax.swing.JPanel DashboardPane;
    private javax.swing.JPanel DashboardPaneClicked;
    private javax.swing.JPanel DoctorPane;
    private javax.swing.JPanel DoctorPaneClicked;
    private javax.swing.JPanel PaymentPane;
    private javax.swing.JPanel PaymentPaneClicked;
    private javax.swing.JPanel SchedulePane;
    private javax.swing.JPanel SchedulePaneClicked;
    private javax.swing.JButton btnSave;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
